
#
#                           ScarletAirDrop
#
#   Ti trovi nella configurazione main del plugin ScarletAirDrop (config.yml).
#                    Plugin creato da MRkillernik
#

# PERMESSI:
# /ad [args] - "ad.admin"

#
# MESSAGE PLACEHOLDERS:
#
# » %cooldown% - Tempo richiesto (formattato)
# » %airdrop% - Numero di airdrop spawnati
#

#
# ALTRO
# » Papi
#   - %scarletairdrop_countdown% countdown formattato
#

Settings:

  # Inizia l'evento anche se non ci sono on
  BETA: true

  AirDrop:

    # Cooldown in secondi
    cooldown: 10800

    # Despawn degli airdrop in secondi
    expire: 600

    min-percentage: 0.75
    max-percentage: 1.25

    min-online: 7

  Loots:

    # Numero minimo di item
    min-item: 3

    # Numero massimo di item
    max-item: 5


  # Imposta i secondi mancanti in cui
  # Vuoi che venga inviato un broadcast
  # Il messaggio verra' automaticamente formattato
  cooldown-message:
    - 1800
    - 300
    - 60
    - 30
    - 10
    - 5
    - 4
    - 3
    - 2
    - 1

  Holo:
    - "&4&lAIRDROP"
    - "&cCliccami per aprire"

Message:
  starting: "&4&lAIRDROP &8// &7Tra &c%cooldown% &7si terra' l'evento AirDrop!"
  started: "&4&lAIRDROP &8// &a&lEvento Iniziato! Airdrop spawnati %airdrop%"
  too-low-players: "&4&lAIRDROP &8// &cL'evento si e' fermato perche' ci sono troppi pochi giocatori!"

Webhook:
  enabled: true
  webhook-url: ""
  avatar-url: ""
  thumbnail-url: ""

  username: "ScarletEvents"

  # \n per andare a capo
  title: "Evento -> Airdrop"
  description: ""

# Imposta con /ad additem
# Oppure rimuovi manualmente mediante il config
Loots:

# Impostale con /ad addlocation
# Oppure rimuovile manualmente mediante il config
Locations: